# Navigation Links

main:
  - name: Home
    url: /
    weight: 5
    pre: '<i class="fas fa-home"></i>'

  - name: Research
    url: /research/
    weight: 10
    pre: '<i class="fas fa-flask"></i>'

  - name: Lab Members
    url: /people/
    weight: 20
    pre: '<i class="fas fa-users"></i>'

  - name: Publications
    url: /publication/
    weight: 30
    pre: '<i class="fas fa-file-alt"></i>'

  - name: Contact
    url: /contact/
    weight: 40
    pre: '<i class="fas fa-envelope"></i>'
